<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_planning</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="vinh.buiquangvinh@hcmut.edu.vn">vinbui</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_target_dependencies</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_eigen</depend>

  <depend>console_bridge_vendor</depend>
  <depend>Eigen3</depend>

  <depend>tesseract_environment</depend>
  <depend>tesseract_command_language</depend>
  <depend>tesseract_task_composer</depend>
  <depend>tesseract_common</depend>
  <depend>tesseract_rosutils</depend>
  <depend>tesseract_motion_planners</depend>
  <depend>tesseract_collision</depend>
  <depend>tesseract_visualization</depend>
  <depend>tesseract_scene_graph</depend>
  <depend>tesseract_urdf</depend>
  <depend>tesseract_monitoring</depend>
  <depend>tesseract_kinematics</depend>
  <depend>tesseract_time_parameterization</depend>

  <depend>trajopt_sqp</depend>
  <depend>trajopt_ifopt</depend>
  <depend>osqp_eigen</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
