controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # --- REQUIRED ---
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # --- Motomini controller ---
    motomini_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # --- Gantry controller ---
    gantry_controller:
      type: joint_trajectory_controller/JointTrajectoryController


# ================================
# Motomini Controller
# ================================
motomini_controller:
  ros__parameters:
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity


# ================================
# Gantry Controller
# ================================
gantry_controller:
  ros__parameters:
    joints:
      - joint_x
      - joint_z
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity