pose_estimator:
  ros__parameters:
    normal_radius: 0.01
  
    feature_radius: 0.025
    ransac_max_corr_dist: 0.02
    ransac_inlier_fraction: 0.10
    ransac_max_iterations: 50000

    icp_max_correspondence_dist: 0.015
  
    icp_max_iterations: 50
  
    debug_mode: true