online_collision_debugger:
  ros__parameters:
    collision_threshold: 0.05
    contact_point_radius: 0.004
    debug_markers_enabled: true
    publish_collision_wrench: true
    publish_contact_debug_text: true
    marker_frame: world
    wrench_frame: world
    wrench_reference_link: tool0
    collision_command_frame: world
    collision_influence_distance: 0.03
    collision_safe_distance: 0.025
    collision_guard_distance: 0.015
    collision_task_distance: 0.005
    collision_stop_distance: 0.001
    collision_k_rep: 0.00023695668539362247
    collision_normal_damping: 4.371144457368462
    collision_k_hold: 80.0
    collision_force_max_per_contact: 8.0
    collision_force_max_total: 15.0
    collision_tangent_enabled: true
    collision_tangent_gain: 1.2885728467932167
    collision_tangent_damping: 3.38432688377824
    collision_tangent_force_max: 3.0
    collision_tangent_force_ratio: 0.3
    collision_tangent_escape_axis: z
    collision_force_attack_hz: 20.0
    collision_force_release_hz: 6.0
    collision_force_slew_rate: 50.0
    force_arrow_min_length: 0.01
    force_arrow_max_length: 0.2
