/**:
  ros__parameters:
    rate_hz: 50.0
    m_pos_min: 0.02762962736270514
    m_pos_max: 0.4703642523584308
    k_pos_min: 472.58699003791304
    k_pos_max: 1490.7949478773587
    zeta_pos: 0.7951723891631814
    m_ori_min: 0.02
    m_ori_max: 0.15
    k_ori_min: 4.0
    k_ori_max: 35.0
    zeta_ori: 1.3
    adaptive_lambda: 58.32803353037327
    adaptive_alpha_pos: 19.013021533750994
    adaptive_alpha_ori: 5.0
    i_gain_pos: 761.4323910069879
    i_gain_ori: 53.98333752943256
    i_clamp_pos: 0.0022216096548073397
    i_clamp_ori: 0.009506916801887975
    i_force_ref: 1.0
    i_force_shape: 10.0
    i_force_min_scale: 0.0
    i_collision_decay_rate: 14.0
    max_cart_linear_vel: 5.0
    max_cart_angular_vel: 1.2
    max_cart_linear_acc: 3.0
    max_cart_angular_acc: 1.0
    w0: 0.001
    k0: 0.01
    enable_seed: false
    integrate_target_vel_to_pose: false
    kp_max: 3.5
    ko_max: 2.5
    kdp: 0.25
    kdo: 0.25
    theta_d_lim: 3.14
    enable_collision_projection: true
    collision_goal_suppression: true
    collision_guard_distance: 0.03
    collision_task_distance: 0.015
    collision_stop_distance: 0.001
    collision_projection_max_gamma: 1.0
    collision_constraint_timeout_sec: 0.2
    collision_force_scale: 1.0
    collision_force_max: 5.0
