/**:
  ros__parameters:
    rate_hz: 50.0
    m_pos_min: 0.007352367614692211
    m_pos_max: 0.3650802891708597
    k_pos_min: 329.87657972805715
    k_pos_max: 1022.7331155480122
    zeta_pos: 0.9371049878432245
    m_ori_min: 0.02
    m_ori_max: 0.15
    k_ori_min: 2.0
    k_ori_max: 15.0
    zeta_ori: 1.0
    adaptive_lambda: 29.84878615827663
    adaptive_alpha_pos: 19.305766863246415
    adaptive_alpha_ori: 5.0
    max_cart_linear_vel: 5.0
    max_cart_angular_vel: 4.0
    max_cart_linear_acc: 3.0
    max_cart_angular_acc: 1.0
    w0: 0.001
    k0: 0.01
    enable_seed: false
    integrate_target_vel_to_pose: false
    kp_max: 3.5
    ko_max: 2.5
    kdp: 0.25
    kdo: 0.25
    theta_d_lim: 3.14
    enable_collision_projection: true
    collision_goal_suppression: true
    collision_guard_distance: 0.03
    collision_task_distance: 0.015
    collision_stop_distance: 0.001
    collision_projection_max_gamma: 1.0
    collision_constraint_timeout_sec: 0.2
    collision_force_scale: 1.0
    collision_force_max: 5.0
